theme = "papercolor-dark"

[editor]
idle-timeout = 0

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
# display-inlay-hints = true

[keys.insert]
C-s = ":w"
C-q = "normal_mode"

[keys.normal]
C-s = ":w"
C-q = ":quit!"

