theme = "catppuccin_mocha"

[editor]
idle-timeout = 0

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true
auto-signature-help = false
display-signature-help-docs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[keys.insert]
"C-/" = "toggle_comments"
C-s = ":w"
C-c = "normal_mode"
C-space = "completion"
C-z = "undo"

[keys.normal]
"C-/" = [ "toggle_comments", ":w" ]
C-s = ":w"
C-q = ":quit!"
C-z = "undo"

[keys.select]
"C-/" = [ "toggle_comments" ]
