theme = "catppuccin_frappe"

[editor]
idle-timeout = 0

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true
auto-signature-help = false
display-signature-help-docs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[keys.insert]
C-s = ":w"
C-c = "normal_mode"
C-space = "signature_help"
C-z = "undo"

[keys.normal]
C-s = ":w"
C-q = ":quit!"
C-z = "undo"
